export default {
  1: "mushrooms",
  2: "cheddar",
  3: "tomatoes",
  4: "salmon",
  5: "mozzarella",
  6: "parmesan",
  7: "blue_cheese",
  8: "salami",
  9: "ham",
  10: "ananas",
  11: "onion",
  12: "bacon",
  13: "chile",
  14: "parmesajalapenon",
  15: "olives",
};
